# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8580e992806f5f32a2e8a7cf4e9615856499ff145c8e78a09609f06805bd2ec00e74eccd6885d692161c682809962118bd7ec09d6ca0e29fd106d7adaed44f3c

test:
  secret_key_base: 5318ed7a195bc919f473c87322fc6d9797c34be515af62be95ffd7455c5e633f0fece486f803cf871ab6edd8c8e9a85cb2b2786b164f9ad3fa19f7ac33d757c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
